version: "3"
services:
  # react-app:
  #   build: ./client
  #   ports: 
  #     - "80:80"
  # api-server:
  #   build: ./server
  #   ports: 
  #     - "5000:5000"
  #   depends_on: 
  #     - mongo
  #     - minio 
  # mongo:
  #   image: mongo
  #   restart: always
  #   ports: 
  #     - "27017:27017"
  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - C:\Users\sraya\Desktop\minio:/data
  #     - C:\Users\sraya\Desktop\minio\config:/root/.minio
  #   environment:
  #     - "MINIO_ACCESS_KEY=miniominio"
  #     - "MINIO_SECRET_KEY=miniominio"
  #   command: server /data

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host add myminio http://minio:9000 miniominio miniominio;
  #     /usr/bin/mc mb myminio/videos;
  #     /usr/bin/mc mb myminio/thumbnail;
  #     /usr/bin/mc policy set download myminio/thumbnail;
  #     /usr/bin/mc policy set download myminio/videos;
  #     exit 0;
  #     "

  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z-31-ga91768d34
    ports:
      - "9000:9000"
    volumes:
      - ./practfix-315623-c4c567022933.json:/credentials.json
      # - C:\Users\sraya\Desktop\minio:/data
      # - C:\Users\sraya\Desktop\minio\config:/root/.minio
    environment:
      - "GOOGLE_APPLICATION_CREDENTIALS=credentials.json"
      #- "MINIO_ROOT_USER=miniominio"
      #- "MINIO_ROOT_PASSWORD=miniominio"
      - "MINIO_ACCESS_KEY=miniominio"
      - "MINIO_SECRET_KEY=miniominio"
    command: gateway gcs practfix-315623
    
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 miniominio miniominio;
      /usr/bin/mc mb myminio/practfix/;
      /usr/bin/mc policy set download myminio/practfix/;
      /usr/bin/mc mb myminio/practfix/jsonzips/;
      /usr/bin/mc policy set download myminio/practfix/jsonzips/;
      /usr/bin/mc mb myminio/practfix/optimalgraph/;
      /usr/bin/mc policy set download myminio/practfix/optimalgraph/;
      /usr/bin/mc mb myminio/practfix/twolinesgraph/;
      usr/bin/mc policy set download myminio/practfix/twolinesgraph/;
      /usr/bin/mc mb myminio/practfix/thumbnail/;
      usr/bin/mc policy set download myminio/practfix/thumbnail/;
      /usr/bin/mc mb myminio/practfix/videos/;
      usr/bin/mc policy set download myminio/practfix/videos/;
      exit 0;
      "